services:
  - type: web
    name: my-application
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SESSION
        value: "RGNK~EOPGL63t"
      - key: DATABASE_URL
        value: "postgresql://myapp_user:RtrffBQYErQ76RxR4TDWb9iyf4sUgGch@dpg-d4agsn3ipnbc739kgkd0-a.oregon-postgres.render.com/myapp_db_f6g4"
          name: my-database
          property: connectionString
